// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: bots.proto

package grpc_bots

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StatusType int32

const (
	StatusType_STATUS_DATA StatusType = 0
	StatusType_URL_DATA    StatusType = 1
)

// Enum value maps for StatusType.
var (
	StatusType_name = map[int32]string{
		0: "STATUS_DATA",
		1: "URL_DATA",
	}
	StatusType_value = map[string]int32{
		"STATUS_DATA": 0,
		"URL_DATA":    1,
	}
)

func (x StatusType) Enum() *StatusType {
	p := new(StatusType)
	*p = x
	return p
}

func (x StatusType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StatusType) Descriptor() protoreflect.EnumDescriptor {
	return file_bots_proto_enumTypes[0].Descriptor()
}

func (StatusType) Type() protoreflect.EnumType {
	return &file_bots_proto_enumTypes[0]
}

func (x StatusType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StatusType.Descriptor instead.
func (StatusType) EnumDescriptor() ([]byte, []int) {
	return file_bots_proto_rawDescGZIP(), []int{0}
}

type GetStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          StatusType             `protobuf:"varint,1,opt,name=type,proto3,enum=bots.StatusType" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatusRequest) Reset() {
	*x = GetStatusRequest{}
	mi := &file_bots_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusRequest) ProtoMessage() {}

func (x *GetStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bots_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusRequest.ProtoReflect.Descriptor instead.
func (*GetStatusRequest) Descriptor() ([]byte, []int) {
	return file_bots_proto_rawDescGZIP(), []int{0}
}

func (x *GetStatusRequest) GetType() StatusType {
	if x != nil {
		return x.Type
	}
	return StatusType_STATUS_DATA
}

type StatusResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	Data          string                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	LatencyMs     float32                `protobuf:"fixed32,4,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResult) Reset() {
	*x = StatusResult{}
	mi := &file_bots_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResult) ProtoMessage() {}

func (x *StatusResult) ProtoReflect() protoreflect.Message {
	mi := &file_bots_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResult.ProtoReflect.Descriptor instead.
func (*StatusResult) Descriptor() ([]byte, []int) {
	return file_bots_proto_rawDescGZIP(), []int{1}
}

func (x *StatusResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *StatusResult) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *StatusResult) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *StatusResult) GetLatencyMs() float32 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

type GetWorldsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorldId       int64                  `protobuf:"varint,1,opt,name=world_id,json=worldId,proto3" json:"world_id,omitempty"`
	BotId         string                 `protobuf:"bytes,2,opt,name=bot_id,json=botId,proto3" json:"bot_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWorldsRequest) Reset() {
	*x = GetWorldsRequest{}
	mi := &file_bots_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWorldsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWorldsRequest) ProtoMessage() {}

func (x *GetWorldsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bots_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWorldsRequest.ProtoReflect.Descriptor instead.
func (*GetWorldsRequest) Descriptor() ([]byte, []int) {
	return file_bots_proto_rawDescGZIP(), []int{2}
}

func (x *GetWorldsRequest) GetWorldId() int64 {
	if x != nil {
		return x.WorldId
	}
	return 0
}

func (x *GetWorldsRequest) GetBotId() string {
	if x != nil {
		return x.BotId
	}
	return ""
}

type WorldsResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	Payload       string                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	LatencyMs     float32                `protobuf:"fixed32,4,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorldsResult) Reset() {
	*x = WorldsResult{}
	mi := &file_bots_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorldsResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorldsResult) ProtoMessage() {}

func (x *WorldsResult) ProtoReflect() protoreflect.Message {
	mi := &file_bots_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorldsResult.ProtoReflect.Descriptor instead.
func (*WorldsResult) Descriptor() ([]byte, []int) {
	return file_bots_proto_rawDescGZIP(), []int{3}
}

func (x *WorldsResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *WorldsResult) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *WorldsResult) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

func (x *WorldsResult) GetLatencyMs() float32 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

type PlatformStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlatformStatusRequest) Reset() {
	*x = PlatformStatusRequest{}
	mi := &file_bots_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlatformStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlatformStatusRequest) ProtoMessage() {}

func (x *PlatformStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bots_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlatformStatusRequest.ProtoReflect.Descriptor instead.
func (*PlatformStatusRequest) Descriptor() ([]byte, []int) {
	return file_bots_proto_rawDescGZIP(), []int{4}
}

type PlatformStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Platforms     []*PlatformInfo        `protobuf:"bytes,1,rep,name=platforms,proto3" json:"platforms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlatformStatusResponse) Reset() {
	*x = PlatformStatusResponse{}
	mi := &file_bots_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlatformStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlatformStatusResponse) ProtoMessage() {}

func (x *PlatformStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bots_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlatformStatusResponse.ProtoReflect.Descriptor instead.
func (*PlatformStatusResponse) Descriptor() ([]byte, []int) {
	return file_bots_proto_rawDescGZIP(), []int{5}
}

func (x *PlatformStatusResponse) GetPlatforms() []*PlatformInfo {
	if x != nil {
		return x.Platforms
	}
	return nil
}

type PlatformInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Name           string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Status         string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"` // online, offline, error
	ConnectedUsers int32                  `protobuf:"varint,3,opt,name=connected_users,json=connectedUsers,proto3" json:"connected_users,omitempty"`
	Features       map[string]bool        `protobuf:"bytes,4,rep,name=features,proto3" json:"features,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PlatformInfo) Reset() {
	*x = PlatformInfo{}
	mi := &file_bots_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlatformInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlatformInfo) ProtoMessage() {}

func (x *PlatformInfo) ProtoReflect() protoreflect.Message {
	mi := &file_bots_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlatformInfo.ProtoReflect.Descriptor instead.
func (*PlatformInfo) Descriptor() ([]byte, []int) {
	return file_bots_proto_rawDescGZIP(), []int{6}
}

func (x *PlatformInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PlatformInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *PlatformInfo) GetConnectedUsers() int32 {
	if x != nil {
		return x.ConnectedUsers
	}
	return 0
}

func (x *PlatformInfo) GetFeatures() map[string]bool {
	if x != nil {
		return x.Features
	}
	return nil
}

var File_bots_proto protoreflect.FileDescriptor

const file_bots_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"bots.proto\x12\x04bots\"8\n" +
	"\x10GetStatusRequest\x12$\n" +
	"\x04type\x18\x01 \x01(\x0e2\x10.bots.StatusTypeR\x04type\"\x80\x01\n" +
	"\fStatusResult\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\x12\x12\n" +
	"\x04data\x18\x03 \x01(\tR\x04data\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\x04 \x01(\x02R\tlatencyMs\"D\n" +
	"\x10GetWorldsRequest\x12\x19\n" +
	"\bworld_id\x18\x01 \x01(\x03R\aworldId\x12\x15\n" +
	"\x06bot_id\x18\x02 \x01(\tR\x05botId\"\x86\x01\n" +
	"\fWorldsResult\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\x12\x18\n" +
	"\apayload\x18\x03 \x01(\tR\apayload\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\x04 \x01(\x02R\tlatencyMs\"\x17\n" +
	"\x15PlatformStatusRequest\"J\n" +
	"\x16PlatformStatusResponse\x120\n" +
	"\tplatforms\x18\x01 \x03(\v2\x12.bots.PlatformInfoR\tplatforms\"\xde\x01\n" +
	"\fPlatformInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12'\n" +
	"\x0fconnected_users\x18\x03 \x01(\x05R\x0econnectedUsers\x12<\n" +
	"\bfeatures\x18\x04 \x03(\v2 .bots.PlatformInfo.FeaturesEntryR\bfeatures\x1a;\n" +
	"\rFeaturesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\bR\x05value:\x028\x01*+\n" +
	"\n" +
	"StatusType\x12\x0f\n" +
	"\vSTATUS_DATA\x10\x00\x12\f\n" +
	"\bURL_DATA\x10\x012\xcc\x01\n" +
	"\vBotsGateway\x12I\n" +
	"\fGetPlatforms\x12\x1b.bots.PlatformStatusRequest\x1a\x1c.bots.PlatformStatusResponse\x127\n" +
	"\tGetStatus\x12\x16.bots.GetStatusRequest\x1a\x12.bots.StatusResult\x129\n" +
	"\tGetWorlds\x12\x16.bots.GetWorldsRequest\x1a\x12.bots.WorldsResult0\x01B\fZ\n" +
	"grpc_bots/b\x06proto3"

var (
	file_bots_proto_rawDescOnce sync.Once
	file_bots_proto_rawDescData []byte
)

func file_bots_proto_rawDescGZIP() []byte {
	file_bots_proto_rawDescOnce.Do(func() {
		file_bots_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_bots_proto_rawDesc), len(file_bots_proto_rawDesc)))
	})
	return file_bots_proto_rawDescData
}

var file_bots_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_bots_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_bots_proto_goTypes = []any{
	(StatusType)(0),                // 0: bots.StatusType
	(*GetStatusRequest)(nil),       // 1: bots.GetStatusRequest
	(*StatusResult)(nil),           // 2: bots.StatusResult
	(*GetWorldsRequest)(nil),       // 3: bots.GetWorldsRequest
	(*WorldsResult)(nil),           // 4: bots.WorldsResult
	(*PlatformStatusRequest)(nil),  // 5: bots.PlatformStatusRequest
	(*PlatformStatusResponse)(nil), // 6: bots.PlatformStatusResponse
	(*PlatformInfo)(nil),           // 7: bots.PlatformInfo
	nil,                            // 8: bots.PlatformInfo.FeaturesEntry
}
var file_bots_proto_depIdxs = []int32{
	0, // 0: bots.GetStatusRequest.type:type_name -> bots.StatusType
	7, // 1: bots.PlatformStatusResponse.platforms:type_name -> bots.PlatformInfo
	8, // 2: bots.PlatformInfo.features:type_name -> bots.PlatformInfo.FeaturesEntry
	5, // 3: bots.BotsGateway.GetPlatforms:input_type -> bots.PlatformStatusRequest
	1, // 4: bots.BotsGateway.GetStatus:input_type -> bots.GetStatusRequest
	3, // 5: bots.BotsGateway.GetWorlds:input_type -> bots.GetWorldsRequest
	6, // 6: bots.BotsGateway.GetPlatforms:output_type -> bots.PlatformStatusResponse
	2, // 7: bots.BotsGateway.GetStatus:output_type -> bots.StatusResult
	4, // 8: bots.BotsGateway.GetWorlds:output_type -> bots.WorldsResult
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_bots_proto_init() }
func file_bots_proto_init() {
	if File_bots_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bots_proto_rawDesc), len(file_bots_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_bots_proto_goTypes,
		DependencyIndexes: file_bots_proto_depIdxs,
		EnumInfos:         file_bots_proto_enumTypes,
		MessageInfos:      file_bots_proto_msgTypes,
	}.Build()
	File_bots_proto = out.File
	file_bots_proto_goTypes = nil
	file_bots_proto_depIdxs = nil
}
