// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: bots.proto

package grpc_bots

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BotsGateway_GetPlatforms_FullMethodName = "/bots.BotsGateway/GetPlatforms"
	BotsGateway_GetStatus_FullMethodName    = "/bots.BotsGateway/GetStatus"
	BotsGateway_GetWorlds_FullMethodName    = "/bots.BotsGateway/GetWorlds"
)

// BotsGatewayClient is the client API for BotsGateway service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BotsGatewayClient interface {
	GetPlatforms(ctx context.Context, in *PlatformStatusRequest, opts ...grpc.CallOption) (*PlatformStatusResponse, error)
	GetStatus(ctx context.Context, in *GetStatusRequest, opts ...grpc.CallOption) (*StatusResult, error)
	GetWorlds(ctx context.Context, in *GetWorldsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WorldsResult], error)
}

type botsGatewayClient struct {
	cc grpc.ClientConnInterface
}

func NewBotsGatewayClient(cc grpc.ClientConnInterface) BotsGatewayClient {
	return &botsGatewayClient{cc}
}

func (c *botsGatewayClient) GetPlatforms(ctx context.Context, in *PlatformStatusRequest, opts ...grpc.CallOption) (*PlatformStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PlatformStatusResponse)
	err := c.cc.Invoke(ctx, BotsGateway_GetPlatforms_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *botsGatewayClient) GetStatus(ctx context.Context, in *GetStatusRequest, opts ...grpc.CallOption) (*StatusResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResult)
	err := c.cc.Invoke(ctx, BotsGateway_GetStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *botsGatewayClient) GetWorlds(ctx context.Context, in *GetWorldsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WorldsResult], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &BotsGateway_ServiceDesc.Streams[0], BotsGateway_GetWorlds_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GetWorldsRequest, WorldsResult]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BotsGateway_GetWorldsClient = grpc.ServerStreamingClient[WorldsResult]

// BotsGatewayServer is the server API for BotsGateway service.
// All implementations must embed UnimplementedBotsGatewayServer
// for forward compatibility.
type BotsGatewayServer interface {
	GetPlatforms(context.Context, *PlatformStatusRequest) (*PlatformStatusResponse, error)
	GetStatus(context.Context, *GetStatusRequest) (*StatusResult, error)
	GetWorlds(*GetWorldsRequest, grpc.ServerStreamingServer[WorldsResult]) error
	mustEmbedUnimplementedBotsGatewayServer()
}

// UnimplementedBotsGatewayServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBotsGatewayServer struct{}

func (UnimplementedBotsGatewayServer) GetPlatforms(context.Context, *PlatformStatusRequest) (*PlatformStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPlatforms not implemented")
}
func (UnimplementedBotsGatewayServer) GetStatus(context.Context, *GetStatusRequest) (*StatusResult, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStatus not implemented")
}
func (UnimplementedBotsGatewayServer) GetWorlds(*GetWorldsRequest, grpc.ServerStreamingServer[WorldsResult]) error {
	return status.Error(codes.Unimplemented, "method GetWorlds not implemented")
}
func (UnimplementedBotsGatewayServer) mustEmbedUnimplementedBotsGatewayServer() {}
func (UnimplementedBotsGatewayServer) testEmbeddedByValue()                     {}

// UnsafeBotsGatewayServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BotsGatewayServer will
// result in compilation errors.
type UnsafeBotsGatewayServer interface {
	mustEmbedUnimplementedBotsGatewayServer()
}

func RegisterBotsGatewayServer(s grpc.ServiceRegistrar, srv BotsGatewayServer) {
	// If the following call panics, it indicates UnimplementedBotsGatewayServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BotsGateway_ServiceDesc, srv)
}

func _BotsGateway_GetPlatforms_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlatformStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BotsGatewayServer).GetPlatforms(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BotsGateway_GetPlatforms_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BotsGatewayServer).GetPlatforms(ctx, req.(*PlatformStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BotsGateway_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BotsGatewayServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BotsGateway_GetStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BotsGatewayServer).GetStatus(ctx, req.(*GetStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BotsGateway_GetWorlds_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetWorldsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(BotsGatewayServer).GetWorlds(m, &grpc.GenericServerStream[GetWorldsRequest, WorldsResult]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BotsGateway_GetWorldsServer = grpc.ServerStreamingServer[WorldsResult]

// BotsGateway_ServiceDesc is the grpc.ServiceDesc for BotsGateway service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BotsGateway_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "bots.BotsGateway",
	HandlerType: (*BotsGatewayServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPlatforms",
			Handler:    _BotsGateway_GetPlatforms_Handler,
		},
		{
			MethodName: "GetStatus",
			Handler:    _BotsGateway_GetStatus_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetWorlds",
			Handler:       _BotsGateway_GetWorlds_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "bots.proto",
}
